const quotes: Array<string> = [
  `"Happiness and freedom begin with a clear understanding of one principle: Some things are within our control, and some things are not." - Epictetus`,
  `"The only way to happiness is to cease worrying about things which are beyond the power of our will." - Epictetus`,
  `"The happiness of your life depends upon the quality of your thoughts." - Marcus Aurelius`,
  `"You have power over your mind, not outside events. Realize this, and you will find strength." - Marcus Aurelius`,
  `"The more we value things outside our control, the less control we have." - Epictetus`,
  `"Waste no more time arguing about what a good person should be. Be one." - Marcus Aurelius`,
  `"It is not the man who has too little that is poor, but the one who hankers after more." - Seneca`,
  `"He who fears death will never do anything worth of a living man." - Seneca`,
  `"No person has the power to have everything they want, but it is in their power not to want what they don't have." - Seneca`,
  `"Do not let the behavior of others destroy your inner peace." - Dalai Lama`,
  `"The best revenge is not to be like your enemy." - Marcus Aurelius`,
  `"The soul becomes dyed with the color of its thoughts." - Marcus Aurelius`,
  `"Waste no more time arguing what a good man should be. Be one." - Marcus Aurelius`,
  `"It's not what happens to you, but how you react to it that matters." - Epictetus`,
  `"He has the most who is most content with the least." - Diogenes`,
  `"If a man knows not to which port he sails, no wind is favorable." - Seneca`,
  `"Don't explain your philosophy. Embody it." - Epictetus`,
  `"Difficulties strengthen the mind, as labor does the body." - Seneca`,
  `"Don't seek for everything to happen as you wish it would, but rather wish that everything happens as it actually will—then your life will be serene." - Epictetus`,
  `"The happiness of your life depends upon the quality of your thoughts." - Marcus Aurelius`,
  `"A gem cannot be polished without friction, nor a man perfected without trials." - Seneca`,
  `"How long are you going to wait before you demand the best for yourself?" - Epictetus`,
  `"Wealth consists not in having great possessions, but in having few wants." - Epictetus`,
  `"The key is to keep company only with people who uplift you, whose presence calls forth your best." - Epictetus`,
  `"He who laughs at himself never runs out of things to laugh at." - Epictetus`,
  `"To be free is the same as to be virtuous." - Epictetus`,
  `"Very little is needed to make a happy life; it is all within yourself, in your way of thinking." - Marcus Aurelius`,
  `"If it is not right, do not do it. If it is not true, do not say it." - Marcus Aurelius`,
  `"Life is very short and anxious for those who forget the past, neglect the present, and fear the future." - Seneca`,
  `"It is not the man who has too little that is poor, but the one who hankers after more." - Seneca`,
  `"The whole future lies in uncertainty: live immediately." - Seneca`,
  `"No person has the power to have everything they want, but it is in their power not to want what they don't have." - Seneca`,
  `"It is not the man who has too little that is poor, but the one who hankers after more." - Seneca`,
  `"We suffer more often in imagination than in reality." - Seneca`,
  `"Don't let the voice of other people's opinions drown out your inner voice." - Steve Jobs`,
  `"The secret of happiness, you see, is not found in seeking more, but in developing the capacity to enjoy less." - Socrates`,
  `"The world is full of wonders, but they become more wonderful when they make us wonder." - M. Aurelius`,
  `"We are more often frightened than hurt, and we suffer more from imagination than from reality." - Seneca`,
  `"To live happily is an inward power of the soul." - Marcus Aurelius`,
  `"What man actually needs is not a tensionless state but rather the striving and struggling for a worthwhile goal." - Viktor E. Frankl`,
  `"Choose not to be harmed, and you won't feel harmed. Don't feel harmed, and you haven't been." - Marcus Aurelius`
]

export default quotes